Prepared Ditto 2.0.0 release notes + announcement blogpost
eclipse/ditto pull request #1032
Opened 2021-04-22 06:11 UTC by thjaeckle

2021-05-03 09:49 UTC, Yannic92 requested changes

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `- ditto-model-connectivity`                 | `ditto-connections/ditto-connections-model` |
thew new module is named ditto-connectivity/ditto-connectivity-model

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `- ditto-model-devops`                       | `ditto-devops/ditto-devops-model` |
ditto-model-devops was merged into ditto-base/ditto-base-api (org.eclipse.ditto.base.api.devops) and is considered to be internal API

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `- ditto-signals-base`                       | `ditto-model-base` |
ditto-base/ditto-base-model

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `-- ditto-signals-acks-base`                 | `ditto-base-model` |
ditto-base/ditto-base-model

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `-- ditto-signals-acks-things`               | `ditto-things-model` |
ditto-things/ditto-things-model

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `-- ditto-signals-announcements-base`        | `ditto-base-model` |
ditto-base/ditto-base-model

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `-- ditto-signals-announcements-policies`    | `ditto-policies-model` |
ditto-policies/ditto-policies-model

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `-- ditto-signals-commands-devops`           | `ditto-devops/ditto-devops-model` |
ditto-model-devops was merged into ditto-base/ditto-base-api (org.eclipse.ditto.base.api.devops) and is considered to be internal API

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `-- ditto-signals-events-base`               | `ditto-base-model` |
ditto-base/ditto-base-model

2021-05-03 09:49 UTC, Yannic92 commented on documentation/src/main/resources/pages/ditto/release_notes_200.md
> +| `org.eclipse.ditto.model.devops`                    | `org.eclipse.ditto.devops.model` |
ditto-model-devops was merged into ditto-base/ditto-base-api (org.eclipse.ditto.base.api.devops) and is considered to be internal API

2021-05-03 12:19 UTC, stmaute commented
Fixed requested changes.

2021-05-06 08:04 UTC, Yannic92 approved these changes

2021-05-06 08:04 UTC, merged