[#1170]: Implement fn:replace
eclipse/ditto pull request #1173
Opened 2021-09-13 08:51 UTC by ctron

This change implements a function of 'fn:replace', which maps to the Java "String::replace" method.

Signed-off-by: Jens Reimann <jreimann@redhat.com>

2021-09-13 10:18 UTC, thjaeckle requested changes
@ctron thanks for this contribution, awesome 👍 
Now indeed a test fails which has to do with the added function, could you please have a look?

And could you please also document the added function in `basic-placeholders.md`?

2021-09-13 11:29 UTC, ctron commented
Ah, indeed. Fixed that locally, let's see what the CI has to say.

I also added it to the docs as suggested.

2021-09-14 11:24 UTC, thjaeckle approved these changes

2021-09-14 11:25 UTC, thjaeckle commented
LGTM 👍

2021-09-14 11:25 UTC, merged