[#1231]: Allow using the dash a part of the namespace
eclipse/ditto pull request #1234
Opened 2021-11-16 16:19 UTC by ctron

Signed-off-by: Jens Reimann <jreimann@redhat.com>

2021-11-17 07:03 UTC, thjaeckle requested changes
Looking good, only I have only some minor remarks regarding javadoc / deprecation marking

2021-11-17 07:03 UTC, thjaeckle commented on base/model/src/main/java/org/eclipse/ditto/base/model/entity/id/RegexPatterns.java
> +     * are not allowed to start with those characters.
we could add `@since 2.2.0` here

2021-11-17 07:03 UTC, thjaeckle commented on base/model/src/main/java/org/eclipse/ditto/base/model/entity/id/RegexPatterns.java
> +    public static final String ALLOWED_NAMESPACE_CHARACTERS_INCLUDING_DOT = ALLOWED_NAMESPACE_CHARACTERS_REGEX_INNER;
please - in addition to the `@deprecated` javadoc (well done :)) - please add annotation `@Deprecated` to the constant as well

2021-11-17 16:01 UTC, ctron commented on base/model/src/main/java/org/eclipse/ditto/base/model/entity/id/RegexPatterns.java
> +     * Adds additional characters that are allowed inside a label. It's defined as separate constant because namespaces
Actually that isn't true to my understanding.

"Label" coming from DNS, is the "segment". So something like: `namespace = label + ( "." label )*`

But I am open to a better term.

2021-11-17 16:42 UTC, thjaeckle commented on base/model/src/main/java/org/eclipse/ditto/base/model/entity/id/RegexPatterns.java
> +     * Adds additional characters that are allowed inside a label. It's defined as separate constant because namespaces
Hm, the `namespace` docs do not directly mention DNS, so "label" did confuse me completely here.
Maybe "namespace segment" could be a term which is understandable without the DNS reference?

2021-11-18 09:10 UTC, ctron commented on base/model/src/main/java/org/eclipse/ditto/base/model/entity/id/RegexPatterns.java
> +     * Adds additional characters that are allowed inside a label. It's defined as separate constant because namespaces
Pushed the change.

2021-11-18 09:19 UTC, thjaeckle approved these changes
Thx, looks good to me 👍

2021-11-18 10:42 UTC, merged

2022-03-24 12:28 UTC, Yannic92 commented
I'm curious. What was the reason to apply the same rules for a "-" as for the "."?
Why would it be a problem to have a namespace started with a "-" or have multiple consecutive dashes?