Accept and test TextMessage with null payload
eclipse/ditto pull request #1505
Opened 2022-10-06 14:21 UTC by tobias-zeptio

Adds the ability to handle TextMessage with null payload, from issue #1503 

Signed-off-by: Tobias Månsson <tobias@zept.io>

2022-10-07 05:52 UTC, tobias-zeptio commented
I tried testing with a BytesMessage, but couldn't figure it out. 

Reading through the code in `AmqpJmsBytesMessageFacade` `BytesMessage` seems to handle a `null` body already.

2022-10-07 13:08 UTC, thjaeckle requested changes
Looks almost good to me - just 2 smaller things to adjust in the test.
The byte `null` payload I could also not understand in the JMS / Qpid facade API .. 
I think it is sufficient to support `null` textMessage.

2022-10-12 07:38 UTC, tobias-zeptio commented
I tried to add a BytesMessage test as well, but can't get it. Creating a empty BytesMessage makes it write-only for some reason, and setting up the body creation using byteStream is beyond me. This is my attempt:

```
    @SafeVarargs // varargs array is not modified or passed around
    private JmsMessage getEmptyJmsByteMessage(final String correlationId, final Map.Entry<String, ?>... headers) {
        try {
            final AmqpJmsBytesMessageFacade messageFacade = new AmqpJmsBytesMessageFacade();
            // give it a connection returning null for all methods to set any AMQP
            // properties at all
            messageFacade.initialize(mock(AmqpConnection.class));
            messageFacade.setCorrelationId(correlationId);

            final JmsMessage message = messageFacade.asJmsMessage();
            JMSPropertyMapper.setPropertiesAndApplicationProperties(messageFacade.asJmsMessage(),
                    Arrays.stream(headers)
                            .collect(Collectors.toMap(Map.Entry::getKey,
                                    e -> e.getValue().toString())),
                    mock(ThreadSafeDittoLoggingAdapter.class));
            message.setAcknowledgeCallback(mockJmsAcknowledgeCallback());
            return message;
        } catch (final JMSException e) {
            throw new JMSRuntimeException(e.getMessage(), e.getErrorCode(), e.getCause());
        }
    }
```

2022-10-12 08:29 UTC, thjaeckle approved these changes

2022-10-12 08:30 UTC, thjaeckle commented
@tobias-zeptio I also tried to add a test with a `null` ByteMessage and failed to create it - the byte message does not seem to support this in the used AMQP client.

If you find out that you still require this also for byte messages, I suggest to create a follow-up PR.

2022-10-12 08:48 UTC, merged