New documentation page for ui
eclipse/ditto pull request #1509
Opened 2022-10-09 14:45 UTC by thfries

Hi there,

Please find this PR to address #1496
After having some hard time to set up the documentation pages 😉, I started a new page for the ui.

@thjaeckle: Not sure, how to exactly use the docker image. Can you please add a remark where the UI can be reached?

Let me know, if the place in the structure fits as proposed.
This is just a first draft, that needs to be refined I think.

Kind regards, Thomas

2022-10-10 08:33 UTC, thjaeckle requested changes
Thanks @thfries for providing the documentation.

I added some inline feedback .. and added how to start the Docker container.
There I noticed that for the Ditto 3.0.0 release the "latest" tag was not uploaded to Docker-Hub and I fixed that :)

2022-10-10 08:33 UTC, thjaeckle commented on documentation/src/main/resources/pages/ditto/user-interface.md
> +docker pull eclipse/ditto-ui:nightly
```suggestion
# to start the latest released UI version:
docker run -p 8088:8080 eclipse/ditto-ui

# or to start the latest nightly instead:
docker run -p 8088:8080 eclipse/ditto-ui:nightly
```

Afterwards, access the Ditto UI in your browser at `http://localhost:8088`

2022-10-10 08:33 UTC, thjaeckle commented on documentation/src/main/resources/pages/ditto/user-interface.md
> +* If it is a Ditto 2 or ditto 3 Version (only relevant if you want to use the connectivity API of Ditto™ prior to version 3)
```suggestion
* whether it is a Ditto 2 or Ditto 3 version (only relevant if you want to use the connectivity API of Ditto™ prior to version 3)
```

2022-10-10 08:33 UTC, thjaeckle commented on documentation/src/main/resources/pages/ditto/user-interface.md
> +| URL search parameter | Description |
```suggestion
| URL query parameter | Description |
```

2022-10-12 05:25 UTC, thfries commented
Hi @thjaeckle,
thanks for the feedback. I processed all remarks. Links with the pre-selected sandbox also work 😀

Open points from my view:
* Shall we review other pages if referring to the ui would make sense?
* Some general quick-start guide on the UI?

But other than that I m ok to start with this page as is. wdyt?

2022-10-12 08:34 UTC, thjaeckle approved these changes
> Hi @thjaeckle, thanks for the feedback. I processed all remarks. Links with the pre-selected sandbox also work 😀
> 
> Open points from my view:
> 
> * Shall we review other pages if referring to the ui would make sense?
> * Some general quick-start guide on the UI?
> 
> But other than that I m ok to start with this page as is. wdyt?

I don't think that adding cross-references to the UI documentation page from many other pages does bring much benefit.
I guess someone searching for a UI will find the new documentation page.

A Quick-Start guide would be good, yes. 
But I would also see that as an add-on to the added documentation.

FMPOV good to merge 👍 
Thanks 🎉

2022-10-12 18:04 UTC, merged