Feature/limit overwrite
eclipse/ditto pull request #892
Opened 2020-11-24 07:50 UTC by VadimGue

Add a more fine granular way for restrict connections and a possibility for connectivity config changes without service restart

2020-11-24 13:17 UTC, thjaeckle commented on json/src/main/java/org/eclipse/ditto/json/JsonFactory.java
> +     * @return returns a new object merged the given {code jsonObject1} and {code jsonObject2}.
This is missing the `@since 1.5.0`

2020-11-25 08:22 UTC, thjaeckle requested changes
Please add the missing mentioned `@since` in the public javadoc in `JsonFactory`

2020-11-25 09:18 UTC, stmaute commented on json/src/main/java/org/eclipse/ditto/json/JsonFactory.java
> +     * @return returns a new object merged the given {code jsonObject1} and {code jsonObject2}.
I have add the missing annotation.

2020-11-25 09:22 UTC, thjaeckle approved these changes

2020-11-25 09:45 UTC, merged