WIP: docs/advanced: add initial draft of data-by-pass
eclipse/ditto pull request #931
Opened 2020-12-24 12:43 UTC by w4tsn

Hello there! I found the time to write up a first draft for the data by-pass pattern mentioned in #545 on our approach.

I've tried to comply roughly around the idea of pattern documents, feel free to comment on that decision.

Some things I want to point out where I think discussion is required:

* Under Discussion I've added first points to benefits, drawbacks and issues that came to my mind. Please add / comment on that as you see fit. Maybe there are actual issues that can be mapped for reference to this doc
* The image does not yet fit into the design of the docs in general, happy for feedback / additions here
* Currently this docs page has no references to the rest of the docs although that might be a good idea tying things together. Any ideas?
* I've added a new section Advanced concepts right under Basic concepts, what do you think?
* The data-by-pass pattern makes a pre-assumption on the pattern to augment things with features from additional services through the messaging API, that may need it's own document
* Currently the Advanced section has no further structure / hierarchy, any objections?

I hope that little christmas present is to your liking and you can actually appreciate it / it's not too rough on the edges :)

2021-01-18 21:14 UTC, w4tsn commented
@thjaeckle in case you missed it, I'd like to hear your opinion on this! And welcome back ;)

2021-01-20 15:27 UTC, thjaeckle commented
@w4tsn thx, I'll have a look at it soon - probably end of this week.

2021-01-22 13:37 UTC, thjaeckle requested changes
Hi @w4tsn and thanks for this first added documentation of advanced patterns, looks very good already 👍 
I added some suggestions (e.g. like writing Ditto always with capital "D" ;)) and mainly have a remark to the added image in combination with the text.

One more thing for the new added "tag" is missing: Please adjust the following file and add the new tag, otherwise it won't show at the bottom of the page:
https://github.com/eclipse/ditto/blob/master/documentation/src/main/resources/_data/tags.yml

2021-01-22 13:37 UTC, thjaeckle commented on documentation/src/main/resources/pages/ditto/advanced-data-by-pass.md
> +With this approach the access to the database is secured via ditto policies and in scope of single things while the data retrieval happens via a performant proxy application without the ditto cluster
```suggestion
With this approach the access to the database is secured via Ditto [policies](basic-policy.html) and in scope of single things while the data retrieval happens via a performant proxy application without the Ditto cluster ever seeing those packages.
```

2021-01-22 13:37 UTC, thjaeckle commented on documentation/src/main/resources/pages/ditto/advanced-data-by-pass.md
> +* Higher performance compared to using just ditto
```suggestion
* Higher performance compared to using just Ditto
```

2021-01-22 13:37 UTC, thjaeckle commented on documentation/src/main/resources/pages/ditto/advanced-data-by-pass.md
> +* The ditto policy system can be utilized to scope and secure data access from clients to databases / -stores
```suggestion
* The Ditto [policy system](basic-policy.html) can be utilized to scope and secure data access from clients to databases / -stores
```

2021-01-22 13:37 UTC, thjaeckle commented on documentation/src/main/resources/pages/ditto/advanced-data-by-pass.md
> +* Managing and communicating custom messaging APIs is not natively supported in ditto, other ways have to be explored to keep APIs consistent
```suggestion
* Managing and communicating custom messaging APIs is not natively supported in Ditto, other ways have to be explored to keep APIs consistent
```

2021-01-22 13:37 UTC, thjaeckle commented on documentation/src/main/resources/pages/ditto/advanced-data-by-pass.md
> +**[othermo GmbH](https://www.othermo.de) uses this for a history-service**: The history service connects to ditto via websockets and hooks into things by answering specific `/history` messages. The m
```suggestion
**[othermo GmbH](https://www.othermo.de) uses this for a history-service**: The history service connects to Ditto via websockets and hooks into things by answering specific `/history` messages. The messages API is translated to InfluxDB queries which then are stored with a randomly generated URL and expiration of 5 minutes at the high-performance proxy. The service then returns the random URL to the client which then follows the 303 to retrieve the actual data.
```

2021-01-25 14:23 UTC, w4tsn commented on documentation/src/main/resources/pages/ditto/advanced-data-by-pass.md
> +{% include image.html file="pages/advanced/data-by-pass-architectural-design.jpg" alt="Architectural Design" caption="Architectural design of the data by-pass pattern showing all actors and their int
Oh yeah, that was sloppy. I'll update the graphic to match the more generalized theme.

2021-01-25 14:50 UTC, w4tsn commented on documentation/src/main/resources/pages/ditto/advanced-data-by-pass.md
> +{% include image.html file="pages/advanced/data-by-pass-architectural-design.jpg" alt="Architectural Design" caption="Architectural design of the data by-pass pattern showing all actors and their int
I've generalized the terms used in the diagram. Please have a look if that's acceptable.

2021-01-26 11:24 UTC, w4tsn commented
@thjaeckle I've added another section on the 'recommended' policy design with this pattern.

2021-01-27 14:45 UTC, thjaeckle approved these changes

2021-01-27 14:45 UTC, thjaeckle commented on documentation/src/main/resources/pages/ditto/advanced-data-by-pass.md
> +{% include image.html file="pages/advanced/data-by-pass-architectural-design.jpg" alt="Architectural Design" caption="Architectural design of the data by-pass pattern showing all actors and their int
@w4tsn looks good, thx 👍

2021-01-27 16:02 UTC, w4tsn commented
@thjaeckle this is ready from my end. Thanks a lot for your review(s)!

2021-01-28 07:17 UTC, merged