Add monitoring features to observe mailbox sizes
eclipse/ditto pull request #946
Opened 2021-01-26 15:35 UTC by jbartelh

In the case that an actor receives more messages than it processes, unbounded mailboxes can cause memory issues.
To spot the error-prone actor in such a case more easily, this PR replaces the default unbounded mailbox from Akka by an unbounded mailbox with additional monitoring capabilities. This mailbox keeps track of it's size, with a constant time complexity, which is used to:
- generate a log entry as soon as a configured mailbox-size-threshold is reached
- and a Prometheus metric ('actor_mailbox_size'), to track for each actor-class the number of messages inside their mailboxes.

2021-01-28 16:18 UTC, Yannic92 requested changes

2021-01-29 09:28 UTC, jbartelh commented on services/utils/akka/src/main/java/org/eclipse/ditto/services/utils/akka/mailbox/MonitoredUnboundedMailboxType.java
> +             throw new IllegalArgumentException("no mailbox owner or system given");
The actor will crash with an `ActorInitializationException`

2021-01-29 09:28 UTC, jbartelh commented on services/utils/akka/src/main/java/org/eclipse/ditto/services/utils/akka/mailbox/MonitoredUnboundedMailboxType.java
> +         final Pattern excludeRegexFilters = Pattern.compile(mailboxConfig.getString(ACTORS_EXCLUDE_REGEX_PATH));
Ah nice, done!

2021-01-29 09:28 UTC, jbartelh commented on services/utils/akka/src/main/java/org/eclipse/ditto/services/utils/akka/mailbox/MonitoredUnboundedMailboxType.java
> +     private static boolean trackActor(final ActorPath path, final Pattern includeRegexFilters,
Done!

2021-01-29 11:51 UTC, Yannic92 commented on services/utils/akka/src/main/java/org/eclipse/ditto/services/utils/akka/mailbox/MonitoredUnboundedMailboxType.java
> +             throw new IllegalArgumentException("no mailbox owner or system given");
Do you think this is a reasonable behaviour for an actor? I would expect it to be restarted and crashing with the same reason over an over again.

2021-01-29 14:37 UTC, Yannic92 approved these changes

2021-01-29 14:38 UTC, merged